apiVersion: v1
kind: Service
metadata:
  name: weather-svc
spec:
  type: NodePort
  selector:
    app: weather
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000
      protocol: TCP